### ISSUE TITLE
안녕하세요. 질문있습니다.

### ISSUE THREAD

**Issue by KKodi-Sera** [g1-tommy/Crawlers#1]
안녕하세요. 주어진 파이썬 공식대로 입력을 해보았는데,

__File__ 이라는 부분을 어떻게 처리해야하는지 잘 모르겠습니다. ㅠㅠ

![1111](https://user-images.githubusercontent.com/57609182/76399240-a4074800-63c1-11ea-8b12-bde70f3ab112.png)

**Comment by g1-tommy** [comment]
ipython에서는 __file__이 동작하지 않습니다. 해당 부분 변경하시거나 CLI로 실행하시기 바랍니다.
